apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: git-admission-control
spec:
  params:
  - name: event-body
  resources:
  - name: pull-request
    type: pullRequest
  - name: policy-repo
    type: git
  tasks:
  - name: setstatus-inprogress
    taskRef:
      name: set-status
    resources:
      inputs:
      - name: pr
        resource: pull-request
      outputs:
      - name: pr
        resource: pull-request
    params:
    - name: status
      value: "in_progress"
#  - name: execute-rules
#    runAfter: [setstatus-inprogress]
#    taskRef:
#      name: apply-policy
#    params:
#    - name: event-body
#      value: $(params.event-body)
#    resources:
#      inputs:
#      - name: policy-repo
#        resource: policy-repo
#      - name: pull-request
#        resource: pull-request
#      outputs:
#      - name: pull-request
#        resource: pull-request
#