apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: stale-github
spec:
  inputs:
    params:
    - name: message
      description: The message to print
      default: This is the default message
      type: string
    resources:
    - name: repo
      type: git
  steps:
  - name: say-message
    image: bash
    command: ["bash", "-c"]
    args:
      - echo '$(inputs.params.message) $(inputs.resources.repo.revision)'
  - name: get-issues
    image: jsternberg/hub
    workingDir: "$(inputs.resources.repo.path)"
    command: ["hub"]
    args: ["issue"]
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: webhook-secret
          key: token
