apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: stale-github
spec:
  inputs:
    params:
    - name: message
      description: The message to print
      default: This is the default message
      type: string
  steps:
  - name: say-message
    image: bash
    command: ["bash", "-c"]
    args:
      - echo '$(inputs.params.message)'